name: Publish Package

on:
  release:
    types: 
      - published

jobs:
  publish-package:
    uses: kad-products/platform/.github/workflows/publish-package.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit